# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nicolas Proshop | Professioneel en op maat gemaakt advies voor de beste bowlingresultaten!
author: Nicolas Van Caelenberghe
email: nicolas@dreamphase.be
description: Op zoek naar materiaal om professioneel te bowlen? Het advies van Nicolas van Caelenberghe is de eerste stap naar betere resultaten. Ik help je graag vrijblijvend verder.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nicolasproshop.be" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

social:
    name: Nicolas Proshop
    links:
        - https://www.instagram.com/nicolasproshop/
        - https://www.facebook.com/nicolasproshop/

# Build settings
markdown: kramdown
plugins:
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-menus

sass:
    sass_dir: _sass
    style: compressed

assets:
    sources:
        - assets/fonts

collections:
    events: 

exclude:
    - functions
    - node_modules
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
